Update TypeScript target to ES6 (#137)
Updating TypeScript target to ES6.

This is needed to avoid issues related to edge cases transpiling es6 classes.

Noticed this, when trying to publish dashboard with expired auth token:

```
node_modules/grafana-dash-gen/grafana/errors.js:62
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^

TypeError: Class constructor StructuredError cannot be invoked without 'new'
    at new ResponseError (node_modules/grafana-dash-gen/grafana/errors.js:62:42)
    at ResponseError.create (node_modules/error/index.js:105:12)
    at grafana-dash-gen/grafana/publish.js:73:40
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```